### ISSUE TITLE
'react' and 'react-native' dependencies

### ISSUE THREAD

**Issue by agilgur5** [seokgyo/react-cloudinary#1]
The package doesn't list them as dependencies or peerDependencies, yet uses both of them. I don't have a React Native app so I don't have React Native installed, and when I try to
`import {...} from 'react-cloudinary'`, I get an error saying `module not found 'react-native'`.

I'm using the `lib/` folder right now and importing everything individually to get around this bug :/

**Comment by seokgyo** [comment]
thanks for the report.
it's on my todo list. I'll fix it soon.

FYI. you can simply use v0.2.x to remove dependency to react-native.
